I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 222, in script
    $ lighter.add_to_bag()
  File "game/script.rpy", line 222, in <module>
    $ lighter.add_to_bag()
  File "game/script.rpy", line 85, in add_to_bag
    bag.append(self.icon)
AttributeError: 'Item' object has no attribute 'icon'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 222, in script
    $ lighter.add_to_bag()
  File "D:\RenPy\renpy-7.4.11-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\RenPy\renpy-7.4.11-sdk\renpy\python.py", line 1049, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 222, in <module>
    $ lighter.add_to_bag()
  File "game/script.rpy", line 85, in add_to_bag
    bag.append(self.icon)
AttributeError: 'Item' object has no attribute 'icon'

Windows-10-10.0.19043 AMD64
Ren'Py 8.0.1.22070801
The Cave 0.1.1.1
Sat Aug 20 10:31:31 2022
